In [292]:
import numpy as np
import pandas as pd

In [293]:
df=pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/19_Bagging/Exercise/heart.csv")
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [294]:
df.shape

(918, 12)

In [295]:
df.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [296]:
df=df[(df.Age>(df.Age.mean()-3*df.Age.std())) & (df.Age<df.Age.mean()+3*df.Age.std())]
df=df[(df.RestingBP>(df.RestingBP.mean()-3*df.RestingBP.std())) & (df.RestingBP<(df.RestingBP.mean()+3*df.RestingBP.std()))]
df=df[(df.Cholesterol>(df.Cholesterol.mean()-3*df.Cholesterol.std())) & (df.Cholesterol<(df.Cholesterol.mean()+3*df.Cholesterol.std()))]
df=df[(df.MaxHR>(df.MaxHR.mean()-3*df.MaxHR.std())) & (df.MaxHR<(df.MaxHR.mean()+3*df.MaxHR.std()))]
df=df[(df.Oldpeak>(df.Oldpeak.mean()-3*df.Oldpeak.std())) & (df.Oldpeak<(df.Oldpeak.mean()+3*df.Oldpeak.std()))]
df=df[(df.HeartDisease>(df.HeartDisease.mean()-3*df.HeartDisease.std())) & (df.HeartDisease<(df.HeartDisease.mean()+3*df.HeartDisease.std()))]

In [297]:
df.shape

(899, 12)

In [298]:
df.ST_Slope.unique()

array(['Up', 'Flat', 'Down'], dtype=object)

In [299]:
df.ExerciseAngina.unique()

array(['N', 'Y'], dtype=object)

In [300]:
df.RestingECG.unique()

array(['Normal', 'ST', 'LVH'], dtype=object)

In [301]:
df.ChestPainType.unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [302]:
df.Sex.unique()

array(['M', 'F'], dtype=object)

In [303]:
df_c = df.copy()
df_c.ExerciseAngina.replace(
    {
        'N': 0,
        'Y': 1
    },
    inplace=True)

df_c.ST_Slope.replace(
    {
        'Down': 1,
        'Flat': 2,
        'Up': 3
    },
    inplace=True
)

df_c.RestingECG.replace(
    {
        'Normal': 1,
        'ST': 2,
        'LVH': 3
    },
    inplace=True)

df_c.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,1,172,0,0.0,3,0
1,49,F,NAP,160,180,0,1,156,0,1.0,2,1
2,37,M,ATA,130,283,0,2,98,0,0.0,3,0
3,48,F,ASY,138,214,0,1,108,1,1.5,2,1
4,54,M,NAP,150,195,0,1,122,0,0.0,3,0

In [304]:
df_ohe=pd.get_dummies(df_c,drop_first=True)
df_ohe

,Age,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA
0,40,140,289,0,1,172,0,0.0,3,0,True,True,False,False
1,49,160,180,0,1,156,0,1.0,2,1,False,False,True,False
2,37,130,283,0,2,98,0,0.0,3,0,True,True,False,False
3,48,138,214,0,1,108,1,1.5,2,1,False,False,False,False
4,54,150,195,0,1,122,0,0.0,3,0,True,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,1,132,0,1.2,2,1,True,False,False,True
914,68,144,193,1,1,141,0,3.4,2,1,True,False,False,False
915,57,130,131,0,1,115,1,1.2,2,1,True,False,False,False
916,57,130,236,0,3,174,0,0.0,2,1,False,True,False,False
917,38,138,175,0,1,173,0,0.0,3,0,True,False,True,False

In [305]:
X=df_ohe.drop("HeartDisease",axis='columns')
y=df_ohe.HeartDisease

In [306]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df_scaled=scaler.fit_transform(X)
df_scaled

array([[-1.42815446,  0.46590022,  0.84963584, ...,  2.06332497,
        -0.5349047 , -0.22955001],
       [-0.47585532,  1.63471366, -0.16812204, ..., -0.48465463,
         1.86949191, -0.22955001],
       [-1.7455875 , -0.1185065 ,  0.79361247, ...,  2.06332497,
        -0.5349047 , -0.22955001],
       ...,
       [ 0.3706328 , -0.1185065 , -0.62564622, ..., -0.48465463,
        -0.5349047 , -0.22955001],
       [ 0.3706328 , -0.1185065 ,  0.35476274, ...,  2.06332497,
        -0.5349047 , -0.22955001],
       [-1.63977649,  0.34901888, -0.21480818, ..., -0.48465463,
         1.86949191, -0.22955001]])

In [307]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df_scaled,y,test_size=0.2)

In [308]:
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score

scores=cross_val_score(SVC(),X,y,cv=5)
scores.mean()

0.6918001241464928

In [309]:
from sklearn.ensemble import BaggingClassifier
bag_model= BaggingClassifier(estimator=SVC(),n_estimators=100,max_samples=0.8,random_state=0)
scores=cross_val_score(bag_model,X,y,cv=5)
scores.mean()

0.685127250155183

In [310]:
from sklearn.tree import DecisionTreeClassifier
scores=cross_val_score(DecisionTreeClassifier(random_state=0),X,y,cv=5)
scores.mean()

0.7151024208566108

In [311]:
bag_model=BaggingClassifier(
estimator=DecisionTreeClassifier(random_state=0),
n_estimators=100,
max_samples=0.9,
oob_score=True,
random_state=0)

scores=cross_val_score(bag_model,X,y,cv=5)
scores.mean()

0.7996896337678461

In [312]:
from sklearn.ensemble import RandomForestClassifier
scores=cross_val_score(RandomForestClassifier(),X,y,cv=5)
scores.mean()

0.8219490999379268