In [11]:
import numpy as np
import pandas as pd

In [12]:
df=pd.read_csv("/kaggle/input/titanic/train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [13]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)

In [14]:
inputs=df.drop(["Survived"],axis='columns')
target=df.Survived

In [15]:
dummies=pd.get_dummies(inputs.Sex)
dummies.head(3)

   female   male
0   False   True
1    True  False
2    True  False

In [16]:
inputs=pd.concat([inputs,dummies],axis="columns")

In [17]:
inputs.drop(['Sex','male'],axis='columns',inplace=True)

In [18]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(inputs,target,test_size=0.3)

In [20]:
from sklearn.naive_bayes import  GaussianNB
model=GaussianNB

In [21]:
model.fit(X_train,y_train)

TypeError: GaussianNB.fit() missing 1 required positional argument: 'y'

In [ ]:
model.score(X_test,y_test)

In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)